### ISSUE TITLE
SVG Renderer throws an error

### ISSUE THREAD

**Issue by lehnerchristian** [flekschas/piling.js#221] opened 2020-10-07 19:45 UTC
_Commit or branch_: Master

#### Observed behavior

- Error in console when using the SVG Renderer, loading screen does not disappear
![Screenshot from 2020-10-07 21-39-55](https://user-images.githubusercontent.com/1711080/95379469-b577ea80-08e5-11eb-99fb-70b51503be1e.png)

#### Expected behavior

- Working pilingJS with 5 SVG images

#### Steps to reproduce

See https://codepen.io/lehnerchristian/pen/LYZYWMo?editors=1111 and open browser console

The error is thrown in this line: https://github.com/flekschas/piling.js/blob/abec7fb3be24d0fbf7b72f0e41ecc3deea8ef8da/src/svg-renderer.js#L39
Probably catching the error would give us a better error message (I gladly will submit a PR for the error handling, if you'd like)

**Comment by flekschas** [comment] 2020-10-08 10:58
Thanks for reporting the issue and setting up the codepen. It turns out the issue was caused by the `<?xml` and `<!DOCTYPE` definitions at the beginning of the external SVG file.

Here's a working example:

```javascript
import createPilingJs, { createSvgRenderer } from 'piling.js';

const create = async (element) => {
  const response = await fetch('/1.svg'); // from https://sample-videos.com/svg/1.svg
  const svg = await response.text();

  return createPilingJs(element, {
    renderer: createSvgRenderer(),
    items: [{ src: svg }],
    darkMode: true,
  })
};
```

Since it's tedious to manually fetch external SVG images, I integrated the `fetch` related part. Hence, the following works in `v0.7.12`:

```javascript
import createPilingJs, { createSvgRenderer } from 'piling.js';

createPilingJs(element, {
  renderer: createSvgRenderer(),
  items: [{ src: '/1.svg' }],
  darkMode: true,
})
```

**Comment by lehnerchristian** [comment] 2020-10-13 14:27
ok, thanks for your reply. I think last week we also had a problem if getting the image returned a 404 - Not Found HTTP status code. however I haven't tried again

**Comment by flekschas** [comment] 2020-10-13 16:59
If the above solution works, can you close the issue?

Regarding the 404 issue, could you open a new issue? In general, piling.js will throw an onload error if the image is not available. One option to not break the initialization could be a placeholder image. However that's not implemented yet.

**Comment by flekschas** [comment] 2020-10-30 21:03
Closing this for now as I assume it's working. Please feel free to reopen if the issue persists

**Closed by flekschas** 2020-10-30 21:03 UTC
Labels: bug
